 version: 2.1 # Use version 2.1 config to get access to orbs, pipelinesaas

 orbs:
   azure-acr: circleci/azure-acr@0.2.0 # Use the Azure ACR orb in your config

 workflows: 
   build-deploy:
     jobs:
       - azure/build-and-push-image:
           azure-username: {AZURE_USERNAME}
           azure-password: {AZURE_PASSWORD}
           dockerfile: Dockerfile # defaults to `Dockerfile`
           path: ./Dockerfile # Defaults to working directory
           login-server-name: containerregistrycd.azurecr.io # e.g. {yourregistryname}.azure.io
           registry-name: containerregistrycd
           repo: https://github.com/Iancrix/CircleCI-NodeApp.git
           filters:
             branches:
               only: master # Only deploys when the commit is on the Master branch

