version: 2.1
jobs:
  #build:
    #...
  deploy:
    machine:
      enabled: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "ef:9e:d1:e3:cd:05:46:b1:a3:d9:2e:25:d3:5d:29:25"
      - run:
          name: Deploy Over SSH
          command: |
             ssh $SSH_USER@$SSH_HOST "echo Hello > hello.txt"

workflows:
  version: 2
  build-and-deploy:
    jobs:
      #- build
      - deploy:
          #requires:
          #  - build # only deploy once build job has completed
          filters:
            branches:
              only: develop # only deploy on the master branch